site_name: Mitarbeiter-innenhandbuch
site_author: Feinheit AG
site_url: https://feinheit.github.io/handbuch/
use_directory_urls: false
theme: material
repo_url: https://github.com/feinheit/handbuch/
markdown_extensions:
  - footnotes
  - smarty
plugins:
  - search:
      lang: ['de']
nav:
- Willkommen!: index.md
- geschichte.md
- strategisch-horizontal-mutig.md
- philosophie.md
- organisation.md
- holacracy.md
- tools.md
- informationen.md
- projektarbeit.md
- sicherheit.md
